# SPDX-License-Identifier: AGPL-3.0-only
# Copyright (c) 2025 Calvin Vette

name: build-push
on:
  push:
    branches: [ main ]
  workflow_dispatch: {}

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
      - name: Check disk usage
        run: df -h
      - uses: actions/checkout@v4
      - name: REUSE lint
        uses: fsfe/reuse-action@v5
      - uses: docker/setup-qemu-action@v3
      - uses: docker/setup-buildx-action@v3
      - uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
      - name: Build & push (amd64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.amd64
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:amd64-${{ github.sha }}
            ghcr.io/${{ github.repository }}:amd64-latest
      - name: Build & push (arm64)
        uses: docker/build-push-action@v6
        with:
          context: .
          file: Dockerfile.arm64
          platforms: linux/arm64
          push: true
          tags: |
            ghcr.io/${{ github.repository }}:arm64-${{ github.sha }}
            ghcr.io/${{ github.repository }}:arm64-latest
