# SPDX-License-Identifier: AGPL-3.0-only
name: reuse-compliance
on:
  push:
  pull_request:

jobs:
  reuse:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: REUSE lint
        uses: fsfe/reuse-action@v5
